import time
from pynput import keyboard, mouse
import pyautogui

# Config
DEFAULT_TARGET_X = 2513
DEFAULT_TARGET_Y = 1475
ALLOW_MANUAL_TARGET_SELECTION = False

# Global state
target_x = DEFAULT_TARGET_X
target_y = DEFAULT_TARGET_Y
target_set = True
clicking_active = True
awaiting_new_target = False
exit_requested = False
last_program_click_time = 0.0

CLICK_INTERVAL_SECONDS = 10
PROGRAM_CLICK_IGNORE_WINDOW = 0.35
RESUME_WITH_ENTER = True
RESUME_WITH_RIGHT_CLICK = True


def set_target(x, y):
    """Store a new target and enable clicking."""
    global target_x, target_y, target_set, clicking_active, awaiting_new_target

    target_x = x
    target_y = y
    target_set = True
    clicking_active = True
    awaiting_new_target = False

    print(f"\nTarget coordinates recorded: X={target_x}, Y={target_y}")
    print("Auto-click is now ACTIVE")
    print("Press F8 to pause/resume, F6 to pick a new target, Esc to exit\n")


def pause_clicking(reason):
    """Pause clicking and print why it paused."""
    global clicking_active

    if clicking_active:
        clicking_active = False
        print(f"\nAuto-click PAUSED ({reason})")
        print("Press F8 to resume, or F6 to pick a new target\n")


def is_program_generated_click(x, y):
    """Ignore the click events generated by pyautogui itself."""
    if target_x is None or target_y is None:
        return False

    recent_click = (time.monotonic() - last_program_click_time) <= PROGRAM_CLICK_IGNORE_WINDOW
    same_spot = abs(x - target_x) <= 1 and abs(y - target_y) <= 1
    return recent_click and same_spot


def on_mouse_click(x, y, button, pressed):
    """Handle mouse click events for target selection and auto-pause."""
    global awaiting_new_target, clicking_active

    if exit_requested:
        return False

    if not pressed or button != mouse.Button.left:
        if not pressed:
            return

        if (
            button == mouse.Button.right
            and RESUME_WITH_RIGHT_CLICK
            and target_set
            and not awaiting_new_target
            and not clicking_active
        ):
            print("\nAuto-click ACTIVE (right-click resume)")
            print("Press F8 to pause/resume, Esc to exit\n")
            clicking_active = True
            return

        if clicking_active:
            pause_clicking("manual mouse click detected")
        return

    if awaiting_new_target:
        set_target(x, y)
        return

    if is_program_generated_click(x, y):
        return

    pause_clicking("manual mouse click detected")


def on_mouse_scroll(x, y, dx, dy):
    """Pause when the user scrolls, which indicates manual interaction."""
    if exit_requested:
        return False

    if clicking_active:
        pause_clicking("manual scroll detected")


def on_key_press(key):
    """Hotkeys for pause/resume/new target, and auto-pause on user typing."""
    global clicking_active, awaiting_new_target, exit_requested

    if key == keyboard.Key.esc:
        exit_requested = True
        clicking_active = False
        print("\nExiting clicker...")
        return False

    if key == keyboard.Key.f6:
        if not ALLOW_MANUAL_TARGET_SELECTION:
            print("\nManual coordinate selection is disabled by configuration.")
            return

        awaiting_new_target = True
        clicking_active = False
        print("\nClick anywhere to set a new target...")
        return

    if key == keyboard.Key.f8:
        if not target_set:
            print("\nNo target selected yet. Click anywhere to set one.")
            return

        clicking_active = not clicking_active
        state = "ACTIVE" if clicking_active else "PAUSED"
        print(f"\nAuto-click {state}")
        return

    if key == keyboard.Key.enter and RESUME_WITH_ENTER and not clicking_active and target_set:
        clicking_active = True
        print("\nAuto-click ACTIVE (Enter resume)")
        return

    if clicking_active:
        pause_clicking("keyboard input detected")


def auto_click_loop():
    """Continuously click while active, but react quickly to pause/exit signals."""
    global last_program_click_time

    while not exit_requested:
        if not target_set or not clicking_active:
            time.sleep(0.1)
            continue

        # Wait first, then click
        waited = 0.0
        while waited < CLICK_INTERVAL_SECONDS and not exit_requested and clicking_active:
            time.sleep(0.1)
            waited += 0.1

        if not clicking_active or exit_requested:
            continue

        last_program_click_time = time.monotonic()
        pyautogui.click(target_x, target_y)
        print(f"[{time.strftime('%H:%M:%S')}] Clicked at ({target_x}, {target_y})")

        waited = 0.0
        while waited < CLICK_INTERVAL_SECONDS and not exit_requested and clicking_active:
            time.sleep(0.1)
            waited += 0.1


def main():
    """Run the clicker with auto-pause and keyboard controls."""
    print("=" * 50)
    print("Screen Auto-Clicker")
    print("=" * 50)
    print("\nInstructions:")
    print(f"1. Default target is ({DEFAULT_TARGET_X}, {DEFAULT_TARGET_Y})")
    print("2. Auto-click runs every 10 seconds")
    print("3. Any keyboard/mouse action pauses auto-click")
    print("4. Press F8 to pause/resume")
    if RESUME_WITH_ENTER:
        print("   Press Enter to resume quickly when paused")
    if RESUME_WITH_RIGHT_CLICK:
        print("   Right-click to resume when paused")
    if ALLOW_MANUAL_TARGET_SELECTION:
        print("5. Press F6 to set a new target")
    else:
        print("5. Manual coordinate selection is disabled")
    print("6. Press Esc to exit\n")

    print(f"Using default target: X={target_x}, Y={target_y}")
    print("Auto-click is now ACTIVE")
    if ALLOW_MANUAL_TARGET_SELECTION:
        print("Press F8 to pause/resume, F6 to pick a new target, Esc to exit\n")
    else:
        print("Press F8 to pause/resume, Esc to exit\n")

    with mouse.Listener(on_click=on_mouse_click, on_scroll=on_mouse_scroll) as mouse_listener:
        with keyboard.Listener(on_press=on_key_press) as keyboard_listener:
            try:
                auto_click_loop()
            except KeyboardInterrupt:
                print("\n\nExiting clicker...")
            finally:
                mouse_listener.stop()
                keyboard_listener.stop()


if __name__ == "__main__":
    main()
